// Generated by rulesync. Do not edit manually.
import { exec } from "node:child_process";
import { promisify } from "node:util";

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const run = promisify(exec);

const MAX_BLOCK_REASON_LENGTH = 2000;
const MAX_SCANNED_REASON_LENGTH = 128_000;

function dropTrailingLoneSurrogate(text: string): string {
  return text.replace(/[\ud800-\udbff]$/, "");
}

function toBlockReason(error: unknown): string {
  const result = error as { stdout?: unknown; stderr?: unknown; code?: unknown } | null;
  const stderr = String(result?.stderr ?? "").trim();
  const stdout = String(result?.stdout ?? "").trim();
  const raw =
    stderr ||
    stdout ||
    (result?.code !== undefined
      ? `Hook command failed with exit code ${result.code}.`
      : error instanceof Error
        ? error.message
        : String(error));
  const scannedTruncated = raw.length > MAX_SCANNED_REASON_LENGTH;
  const scanned = scannedTruncated
    ? dropTrailingLoneSurrogate(raw.slice(0, MAX_SCANNED_REASON_LENGTH))
    : raw;
  const sanitized = scanned
    .replace(/\r\n?/g, "\n")
    .replace(/\u001b\[[0-9;?]*[\u0020-\u002f]*[\u0040-\u007e]/g, "")
    .replace(/\u001b\][^\u0007\u001b]{0,256}(?:\u0007|\u001b\\)/g, "")
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g, "")
    .replace(/[\p{Cf}\p{Zl}\p{Zp}]/gu, "")
    .trim();
  if (!sanitized) return "Hook command failed.";
  if (sanitized.length <= MAX_BLOCK_REASON_LENGTH && !scannedTruncated) return sanitized;
  return `${dropTrailingLoneSurrogate(sanitized.slice(0, MAX_BLOCK_REASON_LENGTH))}...`;
}

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    if (new RegExp("Bash").test(event.toolName)) {
      try {
        await run(".rulesync/hooks/security-guard.sh");
      } catch (error) {
        return { block: true, reason: toBlockReason(error) };
      }
    }
  });
}
