// Generated by rulesync. Do not edit manually.
import type { PluginAPI } from "@ampcode/plugin";

export default function (amp: PluginAPI) {
  amp.on("tool.call", async (event, ctx) => {
    if (new RegExp("Bash").test(event.tool)) {
      try {
        const result = await ctx.$`${{ raw: ".rulesync/hooks/security-guard.sh" }}`;
        if (result.exitCode !== 0) {
          const message = String(result.stderr).trim() || String(result.stdout).trim() || `Hook command failed with exit code ${result.exitCode}.`;
          return { action: "reject-and-continue", message };
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return { action: "reject-and-continue", message };
      }
    }
    return { action: "allow" };
  });
}
